#!/usr/bin/env php
<?php

require __DIR__.'/app/bootstrap.php';

$app = require __DIR__.'/vendor/robmorgan/phinx/app/phinx.php';

if($argv[1] == '-V' || $argv[1] == '--version') {
	echo "RotorCMS by Vantuz - http://visavi.net. version 5.0 dev\n";
}

$app->run();
