INSERT INTO `status` (`id`, `point`, `topoint`, `name`, `color`) VALUES
(1, 0, 249, 'Новичок', ''),
(2, 250, 499, 'Местный', ''),
(3, 500, 999, 'Продвинутый', ''),
(4, 1000, 1999, 'Бывалый', ''),
(5, 2000, 3999, 'Специалист', '#FF8800'),
(6, 4000, 5999, 'Знаток', '#DC143C'),
(7, 6000, 7999, 'Мастер', '#0080FF'),
(8, 8000, 9999, 'Профессионал', '#000000'),
(9, 10000, 14999, 'Гуру', '#32608A'),
(10, 15000, 100000, 'Легенда', '#ff0000');

INSERT INTO `settings` (`name`, `value`) VALUES
('email', 'visavi.net@mail.ru'),
('admin', 'Админ'),
('sitelink', 'rotorcms.ll'),
('sitename', 'Сайт на движке Rotor'),
('sitetitle', 'Rotor 5.0'),
('version', '5.0'),
('guestbook_per_page', 10),
('users_per_page', 10),
('topics_per_page', 10),
('posts_per_page', 10),
('news_per_page', 10),
('description', 'Описание'),
('keywords', 'Ключевые слова');

TRUNCATE TABLE `smiles`;
INSERT INTO `smiles` (`id`, `name`, `code`) VALUES
(1, ').gif', ':)'),
(2, '(.gif', ':('),
(3, '4moks.gif', ':4moks'),
(4, 'D.gif', ':D'),
(5, 'E.gif', ':E'),
(6, 'aaa.gif', ':aaa'),
(7, 'agree.gif', ':agree'),
(8, 'airkiss.gif', ':airkiss'),
(9, 'atlet.gif', ':atlet'),
(10, 'baby.gif', ':baby'),
(11, 'bant.gif', ':bant'),
(12, 'be.gif', ':be'),
(13, 'blin.gif', ':blin'),
(14, 'blum.gif', ':blum'),
(15, 'bomba.gif', ':bomba'),
(16, 'bounce.gif', ':bounce'),
(17, 'bugaga.gif', ':bugaga'),
(18, 'buhoj.gif', ':buhoj'),
(19, 'bwink.gif', ':bwink'),
(20, 'cold.gif', ':cold'),
(21, 'cool.gif', ':cool'),
(22, 'cry.gif', ':cry'),
(23, 'ded.gif', ':ded'),
(24, 'derisive.gif', ':derisive'),
(25, 'drool.gif', ':drool'),
(26, 'duma.gif', ':duma'),
(27, 'exercise.gif', ':exercise'),
(28, 'faq.gif', ':faq'),
(29, 'fermer.gif', ':fermer'),
(30, 'fingal.gif', ':fingal'),
(31, 'flirt.gif', ':flirt'),
(32, 'fuck.gif', ':fuck'),
(33, 'girl_blum.gif', ':girl_blum'),
(34, 'girl_bye.gif', ':girl_bye'),
(35, 'girl_cry.gif', ':girl_cry'),
(36, 'girl_hide.gif', ':girl_hide'),
(37, 'girl_wink.gif', ':girl_wink'),
(38, 'girls.gif', ':girls'),
(39, 'happy.gif', ':happy'),
(40, 'heart.gif', ':heart'),
(41, 'hello.gif', ':hello'),
(42, 'help.gif', ':help'),
(43, 'help2.gif', ':help2'),
(44, 'hi.gif', ':hi'),
(45, 'infat.gif', ':infat'),
(46, 'kiss.gif', ':kiss'),
(47, 'kiss2.gif', ':kiss2'),
(48, 'klass.gif', ':klass'),
(49, 'krut.gif', ':krut'),
(50, 'krutoy.gif', ':krutoy'),
(51, 'ku.gif', ':ku'),
(52, 'kuku.gif', ':kuku'),
(53, 'kulak.gif', ':kulak'),
(54, 'lamer.gif', ':lamer'),
(55, 'love.gif', ':love'),
(56, 'love2.gif', ':love2'),
(58, 'mail.gif', ':mail'),
(59, 'mister.gif', ':mister'),
(60, 'money.gif', ':money'),
(61, 'moped.gif', ':moped'),
(62, 'musik.gif', ':musik'),
(63, 'nea.gif', ':nea'),
(64, 'net.gif', ':net'),
(65, 'neznaju.gif', ':neznaju'),
(66, 'ninja.gif', ':ninja'),
(67, 'no.gif', ':no'),
(68, 'nono.gif', ':nono'),
(69, 'nozh.gif', ':nozh'),
(70, 'nyam.gif', ':nyam'),
(71, 'nyam2.gif', ':icecream'),
(72, 'obana.gif', ':obana'),
(73, 'ogogo.gif', ':ogogo'),
(74, 'oops.gif', ':oops'),
(75, 'opa.gif', ':opa'),
(76, 'otstoy.gif', ':otstoy'),
(77, 'oy.gif', ':oy'),
(78, 'pirat.gif', ':pirat'),
(79, 'pirat2.gif', ':pirat2'),
(80, 'pistolet.gif', ':pistolet'),
(81, 'pistolet2.gif', ':pistolet2'),
(82, 'pizdec.gif', ':shok3'),
(83, 'poisk.gif', ':poisk'),
(84, 'proud.gif', ':proud'),
(85, 'puls.gif', ':puls'),
(86, 'queen.gif', ':queen'),
(87, 'rap.gif', ':rap'),
(88, 'read.gif', ':read'),
(89, 'respekt.gif', ':respekt'),
(90, 'rok.gif', ':rok'),
(91, 'rok2.gif', ':rok2'),
(92, 'senjor.gif', ':senjor'),
(93, 'shok.gif', ':shok'),
(94, 'shok2.gif', ':shok2'),
(95, 'skull.gif', ':skull'),
(96, 'smert.gif', ':smert'),
(97, 'smoke.gif', ':smoke'),
(98, 'spy.gif', ':spy'),
(99, 'strela.gif', ':strela'),
(100, 'svist.gif', ':svist'),
(101, 'tiho.gif', ':tiho'),
(102, 'vau.gif', ':vau'),
(103, 'victory.gif', ':victory'),
(104, 'visavi.gif', ':visavi'),
(105, 'visavi2.gif', ':visavi2'),
(106, 'vtopku.gif', ':vtopku'),
(107, 'wackogirl.gif', ':wackogirl'),
(108, 'xaxa.gif', ':xaxa'),
(109, 'xmm.gif', ':xmm'),
(110, 'yu.gif', ':yu'),
(111, 'zlo.gif', ':zlo'),
(112, 'ban.gif', ':ban'),
(113, 'ban2.gif', ':ban2'),
(114, 'banned.gif', ':banned'),
(115, 'closed.gif', ':closed'),
(116, 'closed2.gif', ':closed2'),
(117, 'devil.gif', ':devil'),
(118, 'flood.gif', ':flood'),
(119, 'flood2.gif', ':flood2'),
(120, 'huligan.gif', ':huligan'),
(121, 'ment.gif', ':ment'),
(122, 'ment2.gif', ':ment2'),
(123, 'moder.gif', ':moder'),
(124, 'nika.gif', ':girlmoder'),
(125, 'offtop.gif', ':offtop'),
(126, 'pravila.gif', ':pravila'),
(127, 'zona.gif', ':zona'),
(128, 'zub.gif', ':zub'),
(129, 'crazy.gif', ':crazy'),
(130, 'paratrooper.gif', ':moder2'),
(131, 'bug.gif', ':bug'),
(132, 'facepalm.gif', ':facepalm'),
(133, 'wall.gif', ':wall'),
(134, 'boss.gif', ':boss');

